# Default Title of Site
title: jumbo-jekyll-theme (the advanced enterprise ready Jekyll theme)
# Description of the site used for default meta description
url: http://jumbojekyll.co.uk
baseurl: ""
description: |-
  The jumbo-jekyll-theme is an advanced enterprise ready Jekyll theme used across the Linaro static websites.
# Destination of the Jekyll site upon build of site.
destination: _site
# Netflify CMS - Default repo branch
branch: master
# Default permalink for blog posts
permalink: /blog/:title/
# Jumbo Jekyll Theme
theme: jumbo-jekyll-theme
# Main Website Repo
github_repo: https://github.com/linaro-marketing/jumbo-jekyll-theme
# Syntax highlighter
highlighter: rouge
# Blog images/thumbs dir
blog_images_dir: assets/images/content/
# Markdown flavour used by Jekyll to parse markdown.
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge # Syntax highlighter for Kramdown.
# Email
email: contact@linaro.org
# Company Address
address:
  - Harston Mill
  - Royston Rd, Harston
  - Cambridge, United Kingdom
  - CB22 7GG
# Default character encoding
encoding: utf-8
# Jekyll configuration for running the site in "Safe" mode.
safe: false
# Files Jekyll will ignore when building the static site.
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .git
  - .asset-cache
  - _static-site
  - .sass-cache
  - _site
  - jumbo-jekyll-theme*.gem
  - jumbo-jekyll-theme*.gemspec
# Sass Configuration for the site styles
sass:
  style: compressed
  load_paths:
    - assets/css
# Compress HTML using the jekyll-tidy plugin.
jekyll_tidy:
  # Toggle compression of HTML
  compress_html: true
  # JS Path added to exclude to stop errors.
  exclude: ["assets/**/*.js", "robots.txt", "admin/config.yml"]
# Permalink style to be used for paginating pages in pagination.html
paginate_path: /blog/:num/
paginate_path_news: /news/:num/
paginate_path_authors: /authors/:num/
# Jekyll Pagination V2 Configuration
pagination:
  # Default pagination path for Jekyll Posts
  # For other permalinks set in the front matter of the post index page
  permalink: /:num/
  # Enabled or not?
  enabled: true
  # Home many posts to display by default
  per_page: 9
  # Number of pages to show either side of the current page i.e - 1, 2, {3}, 4, 5
  trail:
    before: 2
    after: 2
  # Reverse the order of paginated pages
  sort_reverse: true
  # Field to sort posts by when paginating
  sort_field: "date"
# Jekyll pagination v2 autopages configuration.
autopages:
  enabled: false
# Jekyll_get plugin configuration. This will not be needed in all jekyll sites
# only those that are displaying news from the news db or listing Linaro members.
# jekyll_get:
#   data: members
#   json: 'https://github.com/Linaro/db'
# Jekyll defaults - used to set default front matter values to collections and posts
defaults:
  #  Set a default Social Media Image
  - scope:
      path: ""
    values:
      image: /assets/images/social-media-image.png
  - scope:
      type: posts
      path: "_posts"
    values:
      layout: post
      is_post: true
      comments: true
  - scope:
      path: ""
      type: "authors"
    values:
      layout: author
# Jekyll Assets setup
assets:
  # Compress JS Assets - uses the uglifier
  compression: true
  compress:
    js: true
  gzip: true
  # Autoprefixer default settings
  autoprefixer:
    browsers: ["last 2 versions", "> 5%", "IE 9"]
  # These are the paths to look for assets
  sources:
    - assets/js/
    - assets/images/
    - assets/css/
# Jekyll relative links plugin settings
jekyll_relative_links:
  process_all_collections: true
  verbose: 1
relative_links:
  enabled: true
  collections: false
plugins:
  - jekyll-seo-tag
  - japr
  - jekyll_picture_tag
  - jekyll-tidy
  - jekyll-paginate-v2
collections:
  authors:
    output: true
    permalink: /author/:name/
# Make sure that Liquid errors stop the build
liquid:
  error_mode: strict
readme_index:
  enabled: true
  remove_originals: false
include: ["_pages"]
