# Default Title of Site
title: Jumbo Jekyll
# Description of the site used for default meta description
url: http://jumbojekyll.co.uk
baseurl: ""
description: |-
  The Jumbo Jekyll Theme is used across all Linaro static sites.
# Destination of the Jekyll site upon build of site.  
destination: _site
# Default permalink for blog posts
permalink: /blog/:title/ 
# Jumbo Jekyll Theme
theme: jumbo-jekyll-theme
# Syntax highlighter
highlighter: rouge
# Blog images/thumbs dir
blog_images_dir: assets/images/content/
# Markdown flavour used by Jekyll to parse markdown.
markdown: kramdown
# Email
email: contact@linaro.org
# Company Address
address:
  - Harston Mill
  - Royston Rd, Harston
  - Cambridge, United Kingdom
  - CB22 7GG
# Default character encoding
encoding: utf-8
# Jekyll configuration for running the site in "Safe" mode.
safe: false
# Files Jekyll will ignore when building the static site.
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .git
  - .asset-cache
  - _static-site
  - .sass-cache
  - _site
  - package.json
  - node_modules
  - gulpfile.js
# Compress HTML using the jekyll-tidy plugin.
jekyll_tidy: 
    # Toggle compression of HTML
    compress_html: true
    # JS Path added to exclude to stop errors.
    exclude: ["assets/**/*.js"] 
# Permalink style to be used for paginating pages in pagination.html
paginate_path: /blog/:num/
paginate_path_news: /news/:num/
paginate_path_authors: /authors/:num/
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'
  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 9
  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.
  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'
  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'
  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true
  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'
  # Optional, the default tag to use, omit to disable
  tag: ''
  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: '' 
 # Optional,omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 2
  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html
  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'
# Jekyll pagination v2 autopages configuration.
autopages:
  enabled: false
# Jekyll_get plugin configuration. This will not be needed in all jekyll sites
# only those that are displaying news from the news db or listing Linaro members.
# jekyll_get:
#   data: members
#   json: 'https://github.com/Linaro/db'
# Jekyll defaults - used to set default front matter values to collections and posts
defaults:
  #  Set a default Social Media Image
  - scope:
      path: ""
    values:
      image: /assets/images/social-media-image.png
  - scope:
      type: posts 
      path: "_posts"
    values:
      layout: post
      is_post: true
      comments: true
  - scope:
        path: ""
        type: "authors"
    values:
        layout: author
# Jekyll relative links plugin settings    
jekyll_relative_links:
    process_all_collections: true
    verbose: 1
plugins:
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-redirect-from
    - jekyll-paginate-v2
    - jekyll-picture-tag-latest
collections:
  authors:
    output: true
    permalink: /author/:name/
# Make sure that Liquid errors stop the build
liquid:
    error_mode: strict    
readme_index:
    enabled:          true
    remove_originals: false
picture:
  source: "assets/images"
  output: "assets/images/processed"