title: jumbo-jekyll-theme (the advanced enterprise ready Jekyll theme)
url: http://jumbojekyll.co.uk
baseurl: ""
description: |-
  The jumbo-jekyll-theme is an advanced enterprise ready Jekyll theme used across the Linaro static websites.
destination: _site
permalink: /blog/:title/
theme: jumbo-jekyll-theme
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
encoding: utf-8
safe: false
exclude:
  - Gemfile
  - Gemfile.lock
  - .asset_pipeline
  - .gitignore
  - .git
  - .asset-cache
  - _static-site
  - .sass-cache
  - _site
  - jumbo-jekyll-theme*.gem
  - jumbo-jekyll-theme*.gemspec
sass:
  style: compressed
  load_paths:
    - assets/css
plugins:
  - japr
  - jekyll_picture_tag
  - jekyll-tidy
collections:
  authors:
    output: true
    permalink: /author/:name/
liquid:
  error_mode: strict
defaults:
  - scope:
      path: ""
    values:
      layout: flow
  - scope:
      type: posts
      path: "_posts"
    values:
      layout: post
      is_post: true
      comments: true
  - scope:
      path: ""
      type: "authors"
    values:
      layout: author
include: ["_pages"]
# ----------- THEME / WEBSITE CONFIG ---------------------
# Blog images/thumbs dir
blog_images_dir: assets/images/content/
# Email
email: contact@linaro.org
# Company Address
address:
  - Harston Mill
  - Royston Rd, Harston
  - Cambridge, United Kingdom
  - CB22 7GG
# Support for http2 preload features
http2_resources:
  - rel: preload
    as: font
    type: font/woff2
    href: /assets/fonts/lato/Lato-regular.woff2
google_analytics:
  enabled: true
  cookies_popup_title: Test Cookies & Privacy Policy
  cookies_popup_description: >
    Cookies enable test you to use this website to the full extent and to personalize your experience on our sites. They tell us which parts of our websites people have visited, help us measure the effectiveness of ads and web searches and give us insights into user behavior so we can improve our communications with you.
  cookies_links:
    - url: /privacy/
      text: "Privacy Policy"
    - url: /cookies/
      text: "Cookie Policy"
  code: UAXXXXXXB
# Set the site-wide default social media share image.
social_media_share_image: /assets/images/social-media-image.png
# Set the default favicon
favicon: /assets/images/favicon.png
# Site Name - your brand name
name: Jumbo Jekyll Theme
# The blog filler element
blog_filler_element: blog/blog_filler_element.html
# Placeholder avatar
avatar_placeholder: /assets/images/avatar-placeholder.jpg
# Blog Post Image Placholder
post_placeholder: /assets/images/test/background-image1.jpg
# Social Media Links
social_media_channels:
  github:
    url: https://github.com/Linaro
  linkedin:
    url: https://www.linkedin.com/company/1026961
  facebook:
    url: http://facebook.com/LinaroOrg
  youtube:
    url: https://www.youtube.com/linaroorg
  twitter:
    url: https://twitter.com/linaroorg
  instagram:
    url: https://instagram.com/linaroorg
# Disqus Comments Setup
disqus:
    enabled: true
    shortname: http-www-jumbojekyll-co-uk
# Edit on GitHub Settings
edit-on-github:
    enabled: true
    repo: https://www.github.com/linaro-marketing/jumbo-jekyll-theme
    # docs: https://www.github.com/Linaro/website
# Shema.org settings used in the schema.html include.
schema:
  "@type": "Corporation"
  "name": "Linaro"
  "url": "https://www.linaro.org"
  "logo": "https://www.linaro.org/assets/images/content/linaro-logo.png"
  "contactPoint":
    "@type": "ContactPoint"
    "telephone": "01223 400060"
    "contactType": "customer service"
    "availableLanguage": "en"
  "sameAs":
    - "https://facebook.com/LinaroOrg"
    - "https://twitter.com/LinaroOrg"
    - "https://instagram.com/LinaroOrg"
    - "https://www.linkedin.com/company/1026961/"
    - "https://youtube.com/LinaroOrg"
    - "https://github.com/linaro"
    - "https://www.linaro.org"
# FESS search label
search_label: Linaro
# ----------- JEKYLL PLUGINS ---------------------
# -------- jekyll-tidy --------
jekyll_tidy:
  # Toggle compression of HTML
  compress_html: true
  # JS Path added to exclude to stop errors.
  exclude: ["assets/**/*.js", "robots.txt", "admin/config.yml"]
autopages:
  enabled: false
# -------- jekyll_relative_links --------
jekyll_relative_links:
  process_all_collections: true
  verbose: 1
relative_links:
  enabled: true
  collections: false
# -------- jekyll_relative_links --------
readme_index:
  enabled: true
  remove_originals: false
# -------- jekyll_picture_tag --------
picture:
  nomarkdown: false
  source: "assets/images"
  output: "assets/images"
  relative_url: true
# -------- japr --------
asset_pipeline:
  bundle: true
  compress: true
  output_path: assets/js
  gzip: false
